name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore
      working-directory: ./CRM.Client

    - name: Build
      run: dotnet build -c Release -f:net8.0-windows10.0.19041.0
      working-directory: ./CRM.Client

    - name: Add Telerik NuGet Source
      run: dotnet nuget add source https://nuget.telerik.com/v3/index.json --name TelerikOnlineFeed --username purchasing@newwave.com.vn --password 8hgikvztC8WmTU --store-password-in-clear-text

    - name: Restore Dependencies
      run: dotnet restore

    - name: Decode Signing Certificate
      run: |
        echo "${{ secrets.SIGNING_CERTIFICATE_BASE_64_CONTENT }}" > cert.asc
        certutil -decode cert.asc cert.pfx

    - name: Install Signing Certficiate
      run: certutil -user -p ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }} -Silent -importpfx cert.pfx NoRoot

    - name: Publish
      run: dotnet publish -c Release -f:net8.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=${{ secrets.SIGNING_CERTIFICATE_THUMBPRINT }}
      working-directory: ./CRM.Client

    - name: Extract Version
      id: extractVersion
      shell: pwsh
      run: |
        $xml = [Xml] (Get-Content ./CRM.Client/CRM.Client.csproj)
        [string] $version = [Version] $xml.Project.PropertyGroup.ApplicationDisplayVersion
        echo "version=$($version)" >> $env:GITHUB_OUTPUT

    - name: Create Tag
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            ref: 'refs/tags/v${{ steps.extractVersion.outputs.version }}'
          })

    - name: Rename Auto-Update Installer
      shell: pwsh
      run: Rename-Item ./CRM.Client/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/CRM.Client_${{ steps.extractVersion.outputs.version }}.0_Test/CRM.Client_${{ steps.extractVersion.outputs.version }}.0_x64.msix AutoUpdate.msix

    - name: Rename Certificate
      shell: pwsh
      run: Rename-Item ./CRM.Client/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/CRM.Client_${{ steps.extractVersion.outputs.version }}.0_Test/CRM.Client_${{ steps.extractVersion.outputs.version }}.0_x64.cer CRM.Client.cer

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.extractVersion.outputs.version }}
        files: | 
          ./CRM.Client/CRM.Client.appinstaller
          ./CRM.Client/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/CRM.Client_${{ steps.extractVersion.outputs.version }}.0_Test/AutoUpdate.msix
          ./CRM.Client/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/CRM.Client_${{ steps.extractVersion.outputs.version }}.0_Test/CRM.Client.cer
